SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(1, 'ad', 'Andorra', 0.45);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(2, 'ae', 'United Arab Emirates', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(3, 'af', 'Afghanistan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(4, 'ag', 'Antigua and Barbuda', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(5, 'ai', 'Anguilla', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(6, 'al', 'Albania', 0.2);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(7, 'am', 'Armenia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(8, 'an', 'Netherlands Antilles', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(9, 'ao', 'Angola', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(10, 'ar', 'Argentina', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(11, 'at', 'Austria', 0.2);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(12, 'au', 'Australia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(13, 'aw', 'Aruba', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(14, 'az', 'Azerbaijan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(15, 'ba', 'Bosnia and Herzegovina', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(16, 'bb', 'Barbados', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(17, 'bd', 'Bangladesh', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(18, 'be', 'Belgium', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(19, 'bf', 'Burkina Faso', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(20, 'bg', 'Bulgaria', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(21, 'bh', 'Bahrain', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(22, 'bi', 'Burundi', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(23, 'bj', 'Benin', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(24, 'bm', 'Bermuda', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(25, 'bn', 'Brunei Darussalam', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(26, 'bo', 'Bolivia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(27, 'br', 'Brazil', 0.18);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(28, 'bs', 'Bahamas', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(29, 'bt', 'Bhutan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(30, 'bw', 'Botswana', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(31, 'by', 'Belarus', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(32, 'bz', 'Belize', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(33, 'ca', 'Canada', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(34, 'cc', 'Cocos (Keeling) Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(35, 'cd', 'Democratic Republic of the Congo', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(36, 'cf', 'Central African Republic', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(37, 'cg', 'Congo', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(38, 'ch', 'Switzerland', 0.08);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(39, 'ci', 'Cote D\'Ivoire (Ivory Coast)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(40, 'ck', 'Cook Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(41, 'cl', 'Chile', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(42, 'cm', 'Cameroon', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(43, 'cn', 'China', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(44, 'co', 'Colombia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(45, 'cr', 'Costa Rica', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(46, 'cu', 'Cuba', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(47, 'cv', 'Cape Verde', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(48, 'cx', 'Christmas Island', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(49, 'cy', 'Cyprus', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(50, 'cz', 'Czech Republic', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(51, 'de', 'Germany', 0.19);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(52, 'dj', 'Djibouti', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(53, 'dk', 'Denmark', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(54, 'dm', 'Dominica', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(55, 'do', 'Dominican Republic', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(56, 'dz', 'Algeria', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(57, 'ec', 'Ecuador', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(58, 'ee', 'Estonia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(59, 'eg', 'Egypt', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(60, 'eh', 'Western Sahara', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(61, 'er', 'Eritrea', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(62, 'es', 'Spain', 0.21);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(63, 'et', 'Ethiopia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(64, 'fi', 'Finland', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(65, 'fj', 'Fiji', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(66, 'fk', 'Falkland Islands (Malvinas)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(67, 'fm', 'Federated States of Micronesia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(68, 'fo', 'Faroe Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(69, 'fr', 'France', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(70, 'ga', 'Gabon', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(71, 'gb', 'Great Britain (UK)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(72, 'gd', 'Grenada', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(73, 'ge', 'Georgia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(74, 'gf', 'French Guiana', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(75, 'gg', 'NULL', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(76, 'gh', 'Ghana', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(77, 'gi', 'Gibraltar', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(78, 'gl', 'Greenland', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(79, 'gm', 'Gambia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(80, 'gn', 'Guinea', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(81, 'gp', 'Guadeloupe', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(82, 'gq', 'Equatorial Guinea', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(83, 'gr', 'Greece', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(84, 'gs', 'S. Georgia and S. Sandwich Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(85, 'gt', 'Guatemala', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(86, 'gw', 'Guinea-Bissau', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(87, 'gy', 'Guyana', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(88, 'hk', 'Hong Kong', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(89, 'hn', 'Honduras', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(90, 'hr', 'Croatia (Hrvatska)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(91, 'ht', 'Haiti', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(92, 'hu', 'Hungary', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(93, 'id', 'Indonesia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(94, 'ie', 'Ireland', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(95, 'il', 'Israel', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(96, 'in', 'India', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(97, 'iq', 'Iraq', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(98, 'ir', 'Iran', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(99, 'is', 'Iceland', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(100, 'it', 'Italy', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(101, 'jm', 'Jamaica', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(102, 'jo', 'Jordan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(103, 'jp', 'Japan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(104, 'ke', 'Kenya', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(105, 'kg', 'Kyrgyzstan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(106, 'kh', 'Cambodia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(107, 'ki', 'Kiribati', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(108, 'km', 'Comoros', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(109, 'kn', 'Saint Kitts and Nevis', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(110, 'kp', 'Korea (North)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(111, 'kr', 'Korea (South)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(112, 'kw', 'Kuwait', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(113, 'ky', 'Cayman Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(114, 'kz', 'Kazakhstan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(115, 'la', 'Laos', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(116, 'lb', 'Lebanon', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(117, 'lc', 'Saint Lucia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(118, 'li', 'Liechtenstein', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(119, 'lk', 'Sri Lanka', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(120, 'lr', 'Liberia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(121, 'ls', 'Lesotho', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(122, 'lt', 'Lithuania', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(123, 'lu', 'Luxembourg', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(124, 'lv', 'Latvia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(125, 'ly', 'Libya', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(126, 'ma', 'Morocco', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(127, 'mc', 'Monaco', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(128, 'md', 'Moldova', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(129, 'mg', 'Madagascar', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(130, 'mh', 'Marshall Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(131, 'mk', 'Macedonia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(132, 'ml', 'Mali', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(133, 'mm', 'Myanmar', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(134, 'mn', 'Mongolia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(135, 'mo', 'Macao', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(136, 'mp', 'Northern Mariana Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(137, 'mq', 'Martinique', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(138, 'mr', 'Mauritania', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(139, 'ms', 'Montserrat', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(140, 'mt', 'Malta', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(141, 'mu', 'Mauritius', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(142, 'mv', 'Maldives', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(143, 'mw', 'Malawi', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(144, 'mx', 'Mexico', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(145, 'my', 'Malaysia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(146, 'mz', 'Mozambique', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(147, 'na', 'Namibia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(148, 'nc', 'New Caledonia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(149, 'ne', 'Niger', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(150, 'nf', 'Norfolk Island', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(151, 'ng', 'Nigeria', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(152, 'ni', 'Nicaragua', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(153, 'nl', 'Netherlands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(154, 'no', 'Norway', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(155, 'np', 'Nepal', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(156, 'nr', 'Nauru', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(157, 'nu', 'Niue', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(158, 'nz', 'New Zealand (Aotearoa)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(159, 'om', 'Oman', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(160, 'pa', 'Panama', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(161, 'pe', 'Peru', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(162, 'pf', 'French Polynesia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(163, 'pg', 'Papua New Guinea', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(164, 'ph', 'Philippines', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(165, 'pk', 'Pakistan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(166, 'pl', 'Poland', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(167, 'pm', 'Saint Pierre and Miquelon', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(168, 'pn', 'Pitcairn', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(169, 'ps', 'Palestinian Territory', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(170, 'pt', 'Portugal', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(171, 'pw', 'Palau', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(172, 'py', 'Paraguay', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(173, 'qa', 'Qatar', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(174, 're', 'Reunion', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(175, 'ro', 'Romania', 0.24);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(176, 'ru', 'Russian Federation', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(177, 'rw', 'Rwanda', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(178, 'sa', 'Saudi Arabia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(179, 'sb', 'Solomon Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(180, 'sc', 'Seychelles', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(181, 'sd', 'Sudan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(182, 'se', 'Sweden', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(183, 'sg', 'Singapore', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(184, 'sh', 'Saint Helena', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(185, 'si', 'Slovenia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(186, 'sj', 'Svalbard and Jan Mayen', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(187, 'sk', 'Slovakia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(188, 'sl', 'Sierra Leone', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(189, 'sm', 'San Marino', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(190, 'sn', 'Senegal', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(191, 'so', 'Somalia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(192, 'sr', 'Suriname', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(193, 'st', 'Sao Tome and Principe', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(194, 'sv', 'El Salvador', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(195, 'sy', 'Syria', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(196, 'sz', 'Swaziland', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(197, 'tc', 'Turks and Caicos Islands', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(198, 'td', 'Chad', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(199, 'tf', 'French Southern Territories', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(200, 'tg', 'Togo', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(201, 'th', 'Thailand', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(202, 'tj', 'Tajikistan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(203, 'tk', 'Tokelau', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(204, 'tm', 'Turkmenistan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(205, 'tn', 'Tunisia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(206, 'to', 'Tonga', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(207, 'tr', 'Turkey', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(208, 'tt', 'Trinidad and Tobago', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(209, 'tv', 'Tuvalu', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(210, 'tw', 'Taiwan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(211, 'tz', 'Tanzania', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(212, 'ua', 'Ukraine', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(213, 'ug', 'Uganda', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(214, 'uy', 'Uruguay', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(215, 'uz', 'Uzbekistan', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(216, 'vc', 'Saint Vincent and the Grenadines', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(217, 've', 'Venezuela', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(218, 'vg', 'Virgin Islands (British)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(219, 'vi', 'Virgin Islands (U.S.)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(220, 'vn', 'Viet Nam', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(221, 'vu', 'Vanuatu', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(222, 'wf', 'Wallis and Futuna', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(223, 'ws', 'Samoa', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(224, 'ye', 'Yemen', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(225, 'yt', 'Mayotte', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(226, 'za', 'South Africa', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(227, 'zm', 'Zambia', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(228, 'zr', 'Zaire (former)', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(229, 'zw', 'Zimbabwe', 0);
INSERT INTO `country` (`id`, `code`, `name`, `vat`) VALUES(230, 'us', 'United States of America', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
